name: viking66's blog
url: http://viking66.github.io/
description: A blog to document my tinkerings for future reference.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
