name: viking66 blog
url: http://viking66.github.io/
description: A blog to document my tinkerings for future reference.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
kxclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
